# Generated by Django 3.2.12 on 2022-04-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcmtoken',
            old_name='country',
            new_name='token',
        ),
    ]
