language: python
python:
  - 3.9
addons:
  postgresql: "9.6"
services:
  - docker
env:
  - DJANGO=3.1.16
before_install:
  - export DJANGO_SETTINGS_MODULE=api.settings
  - export PYTHONPATH=$HOME/builds/haavardnk/beermonopoly-api
  - export PIP_USE_MIRRORS=true
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

before_script:
  - cd api
  - psql -c "CREATE DATABASE mydb;" -U postgres
script:
  - coverage run --source='.' -m pytest
after_success:
  - codecov

before_deploy:
  - cd ..
deploy:
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: main
