# Generated by Django 3.1.4 on 2020-12-08 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('beerid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brewery', models.CharField(max_length=100)),
                ('abv', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('checkins', models.IntegerField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ibu', models.IntegerField(blank=True, null=True)),
                ('picture', models.URLField(blank=True, null=True)),
                ('vinmonopolet_updated', models.DateTimeField(blank=True, null=True)),
                ('untappd_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
