# Generated by Django 3.1.4 on 2020-12-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='uptappdid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
