# Generated by Django 3.1.4 on 2020-12-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_auto_20201208_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('api_client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('api_client_secret', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
