# Generated by Django 3.1.4 on 2020-12-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0006_auto_20201208_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beerid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
