# Generated by Django 3.1.4 on 2020-12-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0007_auto_20201208_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='picture',
            new_name='label_url',
        ),
    ]
