# Generated by Django 3.1.4 on 2020-12-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0008_auto_20201208_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='verified_match',
            field=models.BooleanField(default=False),
        ),
    ]
