# Generated by Django 3.1.4 on 2020-12-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0009_beer_verified_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='uptappdid',
            new_name='uptappd_id',
        ),
    ]
