# Generated by Django 3.1.4 on 2020-12-09 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0012_beer_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAPI',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('baseurl', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('api_client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('api_client_secret', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SiteSetting',
        ),
    ]
