# Generated by Django 3.1.4 on 2020-12-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0013_auto_20201209_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('phone', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('gps_lat', models.FloatField()),
                ('gps_long', models.FloatField()),
            ],
        ),
    ]
