# Generated by Django 3.1.4 on 2020-12-09 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0015_store_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.beer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.store')),
            ],
            options={
                'unique_together': {('store', 'beer')},
            },
        ),
    ]
