# Generated by Django 3.1.4 on 2020-12-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0016_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='product_selection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
