# Generated by Django 3.1.4 on 2020-12-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0017_beer_product_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='brewery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
