# Generated by Django 3.1.4 on 2020-12-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0018_auto_20201209_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='category',
            new_name='main_category',
        ),
        migrations.AddField(
            model_name='beer',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
