# Generated by Django 3.1.4 on 2020-12-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0019_auto_20201209_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='beerid',
            new_name='vmp_id',
        ),
        migrations.RenameField(
            model_name='beer',
            old_name='name',
            new_name='vmp_name',
        ),
        migrations.RenameField(
            model_name='beer',
            old_name='vinmonopolet_updated',
            new_name='vmp_updated',
        ),
        migrations.RenameField(
            model_name='beer',
            old_name='vinmonopolet_url',
            new_name='vmp_url',
        ),
    ]
