# Generated by Django 3.1.4 on 2020-12-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0020_auto_20201209_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='untappd_updated',
            new_name='untpd_updated',
        ),
        migrations.RenameField(
            model_name='beer',
            old_name='undappd_url',
            new_name='untpd_url',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='untappd_id',
        ),
        migrations.AddField(
            model_name='beer',
            name='untpd_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='untpd_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
