# Generated by Django 3.1.4 on 2020-12-09 11:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0021_auto_20201209_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='label_url',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='beer',
            name='untpd_url',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='beer',
            name='vmp_url',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
