# Generated by Django 3.1.4 on 2020-12-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0022_auto_20201209_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='prioritize_recheck',
            field=models.BooleanField(default=False),
        ),
    ]
