# Generated by Django 3.1.4 on 2020-12-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0025_auto_20201209_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_updated',
        ),
    ]
