# Generated by Django 3.1.4 on 2020-12-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0026_remove_store_store_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
