# Generated by Django 3.1.4 on 2020-12-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0027_store_store_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
