# Generated by Django 3.1.4 on 2020-12-09 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0028_auto_20201209_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='phone',
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='store_updated',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
