# Generated by Django 3.1.4 on 2020-12-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0029_auto_20201209_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='match_manually',
            field=models.BooleanField(default=False),
        ),
    ]
