# Generated by Django 3.1.4 on 2020-12-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0030_beer_match_manually'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
