# Generated by Django 3.1.4 on 2020-12-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0031_matchfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
