# Generated by Django 3.1.4 on 2020-12-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0032_beer_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='storeid',
            new_name='store_id',
        ),
    ]
