# Generated by Django 3.1.4 on 2021-01-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0033_auto_20201211_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFilterCollab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
