# Generated by Django 3.1.4 on 2021-01-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0034_matchfiltercollab'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchFilterCollab',
        ),
    ]
