# Generated by Django 3.1.12 on 2021-06-12 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0035_delete_matchfiltercollab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='label_url',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='beer',
            name='untpd_url',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='beer',
            name='vmp_url',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
