# Generated by Django 3.1.12 on 2021-08-04 08:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0036_auto_20210612_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrongMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_url', models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.URLValidator()])),
                ('accept_change', models.BooleanField(default=False)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.beer')),
            ],
        ),
    ]
