# Generated by Django 3.1.12 on 2021-08-28 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0040_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='checkin_url',
            field=models.CharField(blank=True, max_length=250, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
