# Generated by Django 3.1.12 on 2021-08-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0041_checkin_checkin_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='created_at',
        ),
    ]
