# Generated by Django 3.1.12 on 2021-08-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0042_remove_checkin_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='beer',
        ),
        migrations.AddField(
            model_name='checkin',
            name='beer',
            field=models.ManyToManyField(to='beers.Beer'),
        ),
    ]
