# Generated by Django 3.1.12 on 2021-09-16 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0043_auto_20210830_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchFilter',
        ),
    ]
