# Generated by Django 3.1.12 on 2021-09-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0044_delete_matchfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.beer')),
            ],
        ),
    ]
