# Generated by Django 3.2.7 on 2021-11-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0046_badge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='untpd_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
