# Generated by Django 3.2.9 on 2021-12-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0047_checkin_untpd_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
