# Generated by Django 3.2.9 on 2021-12-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0048_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Option',
        ),
    ]
