# Generated by Django 3.2.9 on 2021-12-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0049_rename_settings_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchManually',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('beers.beer',),
        ),
    ]
