# Generated by Django 3.2.9 on 2022-01-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0052_beer_label_sm_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='area',
            field=models.CharField(default='andeby', max_length=100),
            preserve_default=False,
        ),
    ]
