# Generated by Django 3.2.9 on 2022-01-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0055_remove_beer_main_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_stock_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
