# Generated by Django 3.2.9 on 2022-02-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0057_alter_store_store_stock_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='price_per_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
