# Generated by Django 3.2.11 on 2022-02-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('beers', '0058_beer_price_per_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('beer', models.ManyToManyField(to='beers.Beer')),
            ],
        ),
    ]
