# Generated by Django 3.2.11 on 2022-02-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0060_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
