# Generated by Django 3.2.11 on 2022-02-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0061_alter_release_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
