# Generated by Django 3.2.12 on 2022-02-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0062_release_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
