# Generated by Django 3.2.12 on 2022-02-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0063_checkin_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='post_delivery',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='store_delivery',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
