# Generated by Django 3.2.12 on 2022-02-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0064_auto_20220217_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='allergens',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='aroma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='taste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
