# Generated by Django 3.2.12 on 2022-03-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0066_auto_20220217_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='acid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='aroma',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='bitterness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='freshness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='fullness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='storable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='sugar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='sweetness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='taste',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='vintage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
