# Generated by Django 3.2.12 on 2022-03-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0067_auto_20220330_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='food_pairing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
