# Generated by Django 3.2.12 on 2022-03-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0068_beer_food_pairing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='aroma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='food_pairing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='storable',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='taste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
