# Generated by Django 3.2.12 on 2022-03-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0070_beer_vmp_details_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='raw_materials',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
