# Generated by Django 3.2.12 on 2022-03-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0071_beer_raw_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='acid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
