# Generated by Django 3.2.12 on 2022-04-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0073_rename_vintage_beer_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='raw_materials',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
