# Generated by Django 3.2.13 on 2022-04-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0076_friendlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='method',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
