# Generated by Django 3.2.13 on 2022-07-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0077_alter_beer_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='untpd_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
