# Generated by Django 3.2.16 on 2022-12-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0078_alter_beer_untpd_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
