# Generated by Django 3.2.16 on 2022-12-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0079_checkin_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='abv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='checkin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
