# Generated by Django 3.2.16 on 2023-02-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0081_stock_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='created_at',
        ),
        migrations.AddField(
            model_name='stock',
            name='stocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
