# Generated by Django 3.2.16 on 2023-02-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0083_stock_out_of_stock_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='out_of_stock_at',
            new_name='unstocked_at',
        ),
    ]
