# Generated by Django 3.2.22 on 2023-10-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0086_release_product_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='alcohol_units',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
