# Generated by Django 4.2.16 on 2024-10-23 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0088_tasted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasted',
            name='beer',
        ),
        migrations.AddField(
            model_name='tasted',
            name='beer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beers.beer'),
            preserve_default=False,
        ),
    ]
