# Generated by Django 5.1.5 on 2025-03-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0089_remove_tasted_beer_tasted_beer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='product_selection',
            field=models.CharField(default='Tilleggsutvalget', max_length=50),
        ),
    ]
