# Generated by Django 5.1.5 on 2025-06-18 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0090_alter_beer_product_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrongmatch',
            name='suggested_url',
            field=models.CharField(max_length=250, validators=[django.core.validators.URLValidator()]),
        ),
    ]
