# Generated by Django 5.1.5 on 2025-06-24 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0091_alter_wrongmatch_suggested_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalapi",
            name="baseurl",
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
